// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-yhYF3x1oVx4GVJNnTLYqh8oQYYDeIsY',
    appId: '1:213337915096:web:dba9bce98f0a0162e2e1ad',
    messagingSenderId: '213337915096',
    projectId: 'practice-ef377',
    authDomain: 'practice-ef377.firebaseapp.com',
    storageBucket: 'practice-ef377.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4LWnDXGGxTtbDXTIRsVFx-pUiFlTeadg',
    appId: '1:213337915096:android:d6f83821e7353de0e2e1ad',
    messagingSenderId: '213337915096',
    projectId: 'practice-ef377',
    storageBucket: 'practice-ef377.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjcVagADSvCG1TNErCYLvIoRvcB50UHGo',
    appId: '1:213337915096:ios:9ce0fb39449b34e1e2e1ad',
    messagingSenderId: '213337915096',
    projectId: 'practice-ef377',
    storageBucket: 'practice-ef377.appspot.com',
    iosBundleId: 'com.example.firebaseauthpractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjcVagADSvCG1TNErCYLvIoRvcB50UHGo',
    appId: '1:213337915096:ios:9ce0fb39449b34e1e2e1ad',
    messagingSenderId: '213337915096',
    projectId: 'practice-ef377',
    storageBucket: 'practice-ef377.appspot.com',
    iosBundleId: 'com.example.firebaseauthpractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-yhYF3x1oVx4GVJNnTLYqh8oQYYDeIsY',
    appId: '1:213337915096:web:b6f188cf8ff85ba8e2e1ad',
    messagingSenderId: '213337915096',
    projectId: 'practice-ef377',
    authDomain: 'practice-ef377.firebaseapp.com',
    storageBucket: 'practice-ef377.appspot.com',
  );
}
